### ISSUE TITLE
May I know how to start consul-topology-visualizer

### ISSUE THREAD

**Issue by ZhangShuoAlreadyExists** [vmarchaud/consul-topology-visualizer#2]
Hi,

Thanks for sharing consul-topology-visualizer. But I have a little experience on web stuff, I really don't know how to use it. So can you please share the steps to start consul-topology-visualizer on Ubuntu?
BTW, I already set up a Consul cluster.

**Comment by vmarchaud** [comment]
You could use my docker image, otherwise you just need to reproduce the build of the dockerfile (https://github.com/vmarchaud/consul-topology-visualizer/blob/master/Dockerfile): 
- `yarn install` or `npm install`
- `npx ts-node index.ts`

Also you need to configure the certs with the env variable there: https://github.com/vmarchaud/consul-topology-visualizer#configuration

**Comment by ZhangShuoAlreadyExists** [comment]
Thanks a lot. It works on my side.
